# Generated by Django 4.1.7 on 2023-03-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.SlugField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('is_userboard', models.BooleanField(default=False)),
                ('thread_limit', models.PositiveSmallIntegerField()),
                ('banner', models.FileField(blank=True, null=True, upload_to='')),
                ('order', models.PositiveSmallIntegerField()),
                ('is_adult', models.BooleanField(default=False)),
                ('anon_can_post', models.BooleanField(default=True)),
                ('show_on_main', models.BooleanField(default=True)),
                ('is_deprecated', models.BooleanField(default=False)),
                ('bump_limit', models.PositiveIntegerField()),
                ('max_threads', models.PositiveIntegerField()),
                ('default_name', models.CharField(default='Аноним', max_length=20)),
                ('enable_dices', models.BooleanField(default=False)),
                ('enable_flags', models.BooleanField(default=False)),
                ('enable_likes', models.BooleanField(default=False)),
                ('enable_names', models.BooleanField(default=False)),
                ('enable_oekaki', models.BooleanField(default=False)),
                ('enable_sage', models.BooleanField(default=True)),
                ('enable_subject', models.BooleanField(default=True)),
                ('enable_thread_tags', models.BooleanField(default=False)),
                ('is_protected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=5000)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('order', models.PositiveSmallIntegerField()),
                ('prefix', models.SlugField(max_length=6, unique=True)),
                ('border', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chan.category')),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chan.board')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chan.tag')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chan.category'),
        ),
    ]
