# Generated by Django 4.1.7 on 2023-03-25 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
